const express = require('express');
const puppeteer = require('puppeteer');
const Stripe = require('stripe');
const { v4: uuidv4 } = require('uuid');
const helmet = require('helmet');
const cors = require('cors');
const rateLimit = require('express-rate-limit');
const yaml = require('js-yaml');
const fs = require('fs');
const path = require('path');
const { PDFDocument, StandardFonts, rgb } = require('pdf-lib');
const multer = require('multer');
const axios = require('axios');

const app = express();
const PORT = process.env.PORT || 3000;

const STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY;
const STRIPE_WEBHOOK_SECRET = process.env.STRIPE_WEBHOOK_SECRET;
const API_KEY = process.env.API_KEY || 'dev-api-key-change-me';
const NODE_ENV = process.env.NODE_ENV || 'development';

const stripe = STRIPE_SECRET_KEY ? new Stripe(STRIPE_SECRET_KEY, { apiVersion: '2023-10-16' }) : null;

const TIERS = {
  free: { monthlyRenders: 100, asyncBatch: false, watermark: true, customFonts: false, priority: false, dedicatedWorkers: false },
  starter: { monthlyRenders: 1000, asyncBatch: true, watermark: false, customFonts: false, priority: false, dedicatedWorkers: false, priceId: process.env.STRIPE_PRICE_STARTER },
  pro: { monthlyRenders: 10000, asyncBatch: true, watermark: false, customFonts: true, priority: true, dedicatedWorkers: false, priceId: process.env.STRIPE_PRICE_PRO },
  enterprise: { monthlyRenders: 100000, asyncBatch: true, watermark: false, customFonts: true, priority: true, dedicatedWorkers: true, priceId: process.env.STRIPE_PRICE_ENTERPRISE }
};

const apiKeys = new Map();
const usage = new Map();
const templates = new Map();
const asyncJobs = new Map();
const webhooks = new Map();

const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024 } });

function authenticateApiKey(req, res, next) {
  const authHeader = req.headers.authorization;
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return res.status(401).json({ error: 'Missing or invalid Authorization header. Use: Bearer <api_key>' });
  }
  const apiKey = authHeader.substring(7);
  const keyData = apiKeys.get(apiKey);
  if (!keyData) {
    return res.status(401).json({ error: 'Invalid API key' });
  }
  req.apiKey = apiKey;
  req.keyData = keyData;
  req.tier = keyData.tier || 'free';
  next();
}

function checkRateLimit(req, res, next) {
  const keyData = req.keyData;
  const tierLimits = TIERS[keyData.tier] || TIERS.free;
  const currentMonth = new Date().toISOString().slice(0, 7);
  const usageKey = `${keyData.id}:${currentMonth}`;
  const currentUsage = usage.get(usageKey) || 0;

  if (currentUsage >= tierLimits.monthlyRenders) {
    return res.status(429).json({
      error: 'Monthly render limit exceeded',
      tier: keyData.tier,
      limit: tierLimits.monthlyRenders,
      used: currentUsage,
      upgradeUrl: '/api/billing/portal'
    });
  }
  next();
}

function incrementUsage(apiKeyId) {
  const currentMonth = new Date().toISOString().slice(0, 7);
  const usageKey = `${apiKeyId}:${currentMonth}`;
  usage.set(usageKey, (usage.get(usageKey) || 0) + 1);
}

app.use(helmet({ contentSecurityPolicy: false }));
app.use(cors());
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true, limit: '10mb' }));

const globalLimiter = rateLimit({
  windowMs: 60 * 1000,
  max: 200,
  message: { error: 'Too many requests, please try again later' }
});
app.use(globalLimiter);

let browser = null;
async function getBrowser() {
  if (!browser || !browser.isConnected()) {
    browser = await puppeteer.launch({
      headless: 'new',
      args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage', '--disable-gpu']
    });
  }
  return browser;
}

function generateApiKey(tier = 'free') {
  const apiKey = `pdfgen_${uuidv4().replace(/-/g, '')}`;
  const keyData = { id: uuidv4(), tier, createdAt: new Date().toISOString() };
  apiKeys.set(apiKey, keyData);
  return { apiKey, ...keyData };
}

function renderWatermark(page, text) {
  return page.evaluate((watermarkText) => {
    const style = document.createElement('style');
    style.textContent = `
      @media print {
        body::after {
          content: "${watermarkText}";
          position: fixed;
          top: 50%;
          left: 50%;
          transform: translate(-50%, -50%) rotate(-45deg);
          font-size: 120px;
          color: rgba(0,0,0,0.08);
          z-index: 9999;
          pointer-events: none;
          white-space: nowrap;
          font-family: sans-serif;
        }
      }
    `;
    document.head.appendChild(style);
  }, text);
}

async function generatePdfFromHtml(html, options = {}) {
  const browserInstance = await getBrowser();
  const page = await browserInstance.newPage();

  try {
    await page.setContent(html, { waitUntil: 'networkidle0', timeout: 60000 });

    if (options.watermark) {
      await renderWatermark(page, options.watermarkText || 'Generated by PdfGenerator API - Free Tier');
    }

    if (options.customFonts && options.customFonts.length > 0) {
      for (const font of options.customFonts) {
        await page.addStyleTag({
          content: `@font-face { font-family: '${font.family}'; src: url('${font.url}') format('${font.format || 'woff2'}'); }`
        });
      }
    }

    const pdfOptions = {
      format: options.format || 'A4',
      printBackground: true,
      margin: options.margin || { top: '20mm', right: '15mm', bottom: '20mm', left: '15mm' },
      displayHeaderFooter: options.headerTemplate || options.footerTemplate || options.pageNumbers,
      headerTemplate: options.headerTemplate || '',
      footerTemplate: options.footerTemplate || (options.pageNumbers ? `
        <div style="width: 100%; text-align: center; font-size: 10px; color: #666; padding: 5px;">
          <span class="pageNumber"></span> / <span class="totalPages"></span>
        </div>
      ` : ''),
      preferCSSPageSize: true,
      tagged: options.pdfA || false
    };

    const pdfBuffer = await page.pdf(pdfOptions);
    return pdfBuffer;
  } finally {
    await page.close();
  }
}

async function mergePdfs(pdfBuffers) {
  const mergedPdf = await PDFDocument.create();
  for (const buffer of pdfBuffers) {
    const pdf = await PDFDocument.load(buffer);
    const copiedPages = await mergedPdf.copyPages(pdf, pdf.getPageIndices());
    copiedPages.forEach(page => mergedPdf.addPage(page));
  }
  return Buffer.from(await mergedPdf.save());
}

function applyTemplate(template, data) {
  let html = template.html;
  for (const [key, value] of Object.entries(data)) {
    const regex = new RegExp(`\\{\\{${key}\\}\\}`, 'g');
    html = html.replace(regex, value);
  }
  return html;
}

app.get('/api/health', (req, res) => {
  res.json({
    status: 'ok',
    service: 'pdf-generator-api',
    version: '1.0.0',
    timestamp: new Date().toISOString(),
    browser: browser ? 'connected' : 'not initialized'
  });
});

app.post('/api/keys', async (req, res) => {
  const { tier = 'free', email } = req.body;
  if (!Object.keys(TIERS).includes(tier)) {
    return res.status(400).json({ error: 'Invalid tier', validTiers: Object.keys(TIERS) });
  }
  if (tier !== 'free' && !stripe) {
    return res.status(503).json({ error: 'Stripe not configured. Paid tiers unavailable.' });
  }

  const keyResult = generateApiKey(tier);
  if (tier !== 'free' && stripe) {
    try {
      const customer = await stripe.customers.create({ email, metadata: { apiKeyId: keyResult.id } });
      keyResult.stripeCustomerId = customer.id;
      keyResult.subscriptionUrl = `/api/billing/checkout?priceId=${TIERS[tier].priceId}&customerId=${customer.id}`;
    } catch (e) {
      console.error('Stripe customer creation failed:', e.message);
    }
  }
  res.status(201).json(keyResult);
});

app.post('/api/render', authenticateApiKey, checkRateLimit, async (req, res) => {
  const { html, templateId, data, options = {} } = req.body;
  const tierLimits = TIERS[req.tier] || TIERS.free;

  if (!html && !templateId) {
    return res.status(400).json({ error: 'Either html or templateId is required' });
  }

  let finalHtml = html;
  if (templateId) {
    const template = templates.get(templateId);
    if (!template) {
      return res.status(404).json({ error: 'Template not found' });
    }
    finalHtml = applyTemplate(template, data || {});
  }

  const renderOptions = {
    format: options.format || 'A4',
    margin: options.margin,
    headerTemplate: options.headerTemplate,
    footerTemplate: options.footerTemplate,
    pageNumbers: options.pageNumbers !== false,
    watermark: tierLimits.watermark && !options.removeWatermark,
    watermarkText: options.watermarkText,
    customFonts: tierLimits.customFonts ? (options.customFonts || []) : [],
    pdfA: options.pdfA || false
  };

  try {
    const pdfBuffer = await generatePdfFromHtml(finalHtml, renderOptions);
    incrementUsage(req.keyData.id);

    res.set({
      'Content-Type': 'application/pdf',
      'Content-Length': pdfBuffer.length,
      'X-Renders-Remaining': tierLimits.monthlyRenders - (usage.get(`${req.keyData.id}:${new Date().toISOString().slice(0,7)}`) || 0)
    });
    res.send(pdfBuffer);
  } catch (error) {
    console.error('Render error:', error);
    res.status(500).json({ error: 'PDF generation failed', details: error.message });
  }
});

app.post('/api/templates', authenticateApiKey, async (req, res) => {
  const { name, html, description } = req.body;
  if (!name || !html) {
    return res.status(400).json({ error: 'name and html are required' });
  }
  const templateId = uuidv4();
  templates.set(templateId, { id: templateId, name, html, description, createdAt: new Date().toISOString(), ownerId: req.keyData.id });
  res.status(201).json({ id: templateId, name, description });
});

app.get('/api/templates', authenticateApiKey, (req, res) => {
  const userTemplates = Array.from(templates.values()).filter(t => t.ownerId === req.keyData.id);
  res.json(userTemplates);
});

app.get('/api/templates/:id', authenticateApiKey, (req, res) => {
  const template = templates.get(req.params.id);
  if (!template || template.ownerId !== req.keyData.id) {
    return res.status(404).json({ error: 'Template not found' });
  }
  res.json(template);
});

app.delete('/api/templates/:id', authenticateApiKey, (req, res) => {
  const template = templates.get(req.params.id);
  if (!template || template.ownerId !== req.keyData.id) {
    return res.status(404).json({ error: 'Template not found' });
  }
  templates.delete(req.params.id);
  res.status(204).send();
});

app.post('/api/batch', authenticateApiKey, async (req, res) => {
  const tierLimits = TIERS[req.tier] || TIERS.free;
  if (!tierLimits.asyncBatch) {
    return res.status(403).json({ error: 'Async batch processing not available on free tier. Upgrade to Starter or higher.' });
  }

  const { items, webhookUrl, options = {} } = req.body;
  if (!items || !Array.isArray(items) || items.length === 0) {
    return res.status(400).json({ error: 'items array is required' });
  }
  if (items.length > 100) {
    return res.status(400).json({ error: 'Maximum 100 items per batch' });
  }

  const jobId = uuidv4();
  const job = {
    id: jobId,
    status: 'pending',
    items: items.map((item, index) => ({ ...item, index, status: 'pending' })),
    webhookUrl,
    options,
    createdAt: new Date().toISOString(),
    completedAt: null,
    results: []
  };
  asyncJobs.set(jobId, job);

  processBatchJob(jobId, req.keyData.id, req.tier).catch(console.error);

  res.status(202).json({ jobId, status: 'pending', statusUrl: `/api/batch/${jobId}` });
});

async function processBatchJob(jobId, apiKeyId, tier) {
  const job = asyncJobs.get(jobId);
  if (!job) return;

  job.status = 'processing';
  const tierLimits = TIERS[tier] || TIERS.free;

  for (const item of job.items) {
    item.status = 'processing';
    try {
      let finalHtml = item.html;
      if (item.templateId) {
        const template = templates.get(item.templateId);
        if (template) finalHtml = applyTemplate(template, item.data || {});
      }

      const renderOptions = {
        format: job.options.format || 'A4',
        margin: job.options.margin,
        headerTemplate: job.options.headerTemplate,
        footerTemplate: job.options.footerTemplate,
        pageNumbers: job.options.pageNumbers !== false,
        watermark: tierLimits.watermark,
        customFonts: tierLimits.customFonts ? (job.options.customFonts || []) : [],
        pdfA: job.options.pdfA || false
      };

      const pdfBuffer = await generatePdfFromHtml(finalHtml, renderOptions);
      incrementUsage(apiKeyId);

      const base64Pdf = pdfBuffer.toString('base64');
      item.status = 'completed';
      item.result = { pdfBase64: base64Pdf, size: pdfBuffer.length };
      job.results.push({ index: item.index, pdfBase64: base64Pdf, size: pdfBuffer.length });
    } catch (error) {
      item.status = 'failed';
      item.error = error.message;
      job.results.push({ index: item.index, error: error.message });
    }
  }

  job.status = job.items.every(i => i.status === 'completed') ? 'completed' : 'partial_failure';
  job.completedAt = new Date().toISOString();

  if (job.webhookUrl) {
    try {
      await axios.post(job.webhookUrl, {
        jobId,
        status: job.status,
        results: job.results,
        completedAt: job.completedAt
      }, { timeout: 10000 });
    } catch (e) {
      console.error('Webhook delivery failed:', e.message);
    }
  }
}

app.get('/api/batch/:jobId', authenticateApiKey, (req, res) => {
  const job = asyncJobs.get(req.params.jobId);
  if (!job) return res.status(404).json({ error: 'Job not found' });
  res.json(job);
});

app.post('/api/merge', authenticateApiKey, checkRateLimit, upload.array('pdfs'), async (req, res) => {
  if (!req.files || req.files.length < 2) {
    return res.status(400).json({ error: 'At least 2 PDF files required' });
  }

  try {
    const pdfBuffers = req.files.map(f => f.buffer);
    const mergedBuffer = await mergePdfs(pdfBuffers);
    incrementUsage(req.keyData.id);

    res.set({
      'Content-Type': 'application/pdf',
      'Content-Length': mergedBuffer.length
    });
    res.send(mergedBuffer);
  } catch (error) {
    console.error('Merge error:', error);
    res.status(500).json({ error: 'PDF merge failed', details: error.message });
  }
});

app.post('/api/billing/checkout', authenticateApiKey, async (req, res) => {
  if (!stripe) return res.status(503).json({ error: 'Stripe not configured' });
  const { priceId, customerId } = req.body;
  if (!priceId) return res.status(400).json({ error: 'priceId required' });

  try {
    const session = await stripe.checkout.sessions.create({
      mode: 'subscription',
      payment_method_types: ['card'],
      line_items: [{ price: priceId, quantity: 1 }],
      customer: customerId || undefined,
      success_url: `${req.headers.origin || 'http://localhost:3000'}/success?session_id={CHECKOUT_SESSION_ID}`,
      cancel_url: `${req.headers.origin || 'http://localhost:3000'}/cancel`,
      metadata: { apiKeyId: req.keyData.id }
    });
    res.json({ url: session.url, sessionId: session.id });
  } catch (e) {
    console.error('Checkout error:', e);
    res.status(500).json({ error: 'Failed to create checkout session' });
  }
});

app.post('/api/billing/portal', authenticateApiKey, async (req, res) => {
  if (!stripe) return res.status(503).json({ error: 'Stripe not configured' });
  const keyData = req.keyData;
  if (!keyData.stripeCustomerId) {
    return res.status(400).json({ error: 'No Stripe customer associated. Subscribe first.' });
  }
  try {
    const session = await stripe.billingPortal.sessions.create({
      customer: keyData.stripeCustomerId,
      return_url: req.headers.origin || 'http://localhost:3000'
    });
    res.json({ url: session.url });
  } catch (e) {
    res.status(500).json({ error: 'Failed to create portal session' });
  }
});

app.post('/api/webhooks/stripe', express.raw({ type: 'application/json' }), async (req, res) => {
  if (!stripe || !STRIPE_WEBHOOK_SECRET) {
    return res.status(400).send('Webhook secret not configured');
  }
  const sig = req.headers['stripe-signature'];
  let event;
  try {
    event = stripe.webhooks.constructEvent(req.body, sig, STRIPE_WEBHOOK_SECRET);
  } catch (err) {
    console.error('Webhook signature verification failed:', err.message);
    return res.status(400).send(`Webhook Error: ${err.message}`);
  }

  if (event.type === 'checkout.session.completed') {
    const session = event.data.object;
    const apiKeyId = session.metadata?.apiKeyId;
    if (apiKeyId) {
      for (const [key, data] of apiKeys.entries()) {
        if (data.id === apiKeyId) {
          data.tier = getTierFromPriceId(session.subscription?.price_id) || 'starter';
          data.stripeCustomerId = session.customer;
          data.stripeSubscriptionId = session.subscription;
          apiKeys.set(key, data);
          break;
        }
      }
    }
  } else if (event.type === 'customer.subscription.deleted') {
    const subscription = event.data.object;
    for (const [key, data] of apiKeys.entries()) {
      if (data.stripeSubscriptionId === subscription.id) {
        data.tier = 'free';
        apiKeys.set(key, data);
        break;
      }
    }
  }

  res.json({ received: true });
});

function getTierFromPriceId(priceId) {
  for (const [tier, config] of Object.entries(TIERS)) {
    if (config.priceId === priceId) return tier;
  }
  return null;
}

app.get('/api/usage', authenticateApiKey, (req, res) => {
  const currentMonth = new Date().toISOString().slice(0, 7);
  const usageKey = `${req.keyData.id}:${currentMonth}`;
  const currentUsage = usage.get(usageKey) || 0;
  const tierLimits = TIERS[req.tier] || TIERS.free;
  res.json({
    tier: req.tier,
    currentMonth,
    used: currentUsage,
    limit: tierLimits.monthlyRenders,
    remaining: Math.max(0, tierLimits.monthlyRenders - currentUsage),
    features: tierLimits
  });
});

app.use((err, req, res, next) => {
  console.error('Unhandled error:', err);
  res.status(500).json({ error: 'Internal server error' });
});

app.listen(PORT, () => {
  console.log(`PdfGenerator API listening on port ${PORT}`);
  console.log(`Health check: http://localhost:${PORT}/api/health`);
  if (NODE_ENV === 'development') {
    const devKey = generateApiKey('free');
    console.log(`Dev API Key: ${devKey.apiKey}`);
  }
});

process.on('SIGTERM', async () => {
  if (browser) await browser.close();
  process.exit(0);
});
