require('dotenv').config();

const { Worker } = require('bullmq');
const Redis = require('ioredis');
const puppeteer = require('puppeteer');
const { PDFDocument, rgb, degrees, StandardFonts } = require('pdf-lib');

if (!process.env.REDIS_URL) {
  throw new Error('REDIS_URL is required to run the worker');
}

const redis = new Redis(process.env.REDIS_URL, {
  maxRetriesPerRequest: null,
  enableReadyCheck: false
});

const tierLimits = {
  free: { watermark: true, customFonts: false },
  starter: { watermark: false, customFonts: true },
  pro: { watermark: false, customFonts: true },
  enterprise: { watermark: false, customFonts: true }
};

let browser = null;

async function getBrowser() {
  if (!browser || !browser.isConnected()) {
    browser = await puppeteer.launch({
      headless: true,
      executablePath: process.env.PUPPETEER_EXECUTABLE_PATH || undefined,
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-gpu',
        '--no-zygote'
      ]
    });
  }
  return browser;
}

async function addWatermark(pdfBytes, text) {
  const pdf = await PDFDocument.load(pdfBytes);
  const font = await pdf.embedFont(StandardFonts.Helvetica);

  for (const page of pdf.getPages()) {
    const { width, height } = page.getSize();
    const size = Math.min(48, Math.max(18, width / 12));
    const textWidth = font.widthOfTextAtSize(text, size);
    page.drawText(text, {
      x: (width - textWidth) / 2,
      y: height / 2,
      size,
      font,
      color: rgb(0.6, 0.6, 0.6),
      opacity: 0.3,
      rotate: degrees(-35)
    });
  }

  return Buffer.from(await pdf.save());
}

async function addArchiveMetadata(pdfBytes) {
  const pdf = await PDFDocument.load(pdfBytes);
  pdf.setTitle('Archived PDF document');
  pdf.setAuthor('PdfGenerator API');
  pdf.setCreator('PdfGenerator API');
  pdf.setProducer('PdfGenerator API');
  pdf.setCreationDate(new Date());
  pdf.setModificationDate(new Date());
  return Buffer.from(await pdf.save({ useObjectStreams: false }));
}

async function renderPdf(html, css, options, limits) {
  const browserInstance = await getBrowser();
  const page = await browserInstance.newPage();

  try {
    const fontStyles = limits.customFonts && Array.isArray(options.customFonts)
      ? options.customFonts.map((fontUrl, index) => {
        return `@font-face{font-family:"CustomFont${index}";src:url("${fontUrl}") format("woff2");font-display:swap;}`;
      }).join('')
      : '';

    const documentHtml = `<!doctype html><html><head><meta charset="utf-8"><style>${fontStyles}${css || ''}</style></head><body>${html}</body></html>`;
    await page.setContent(documentHtml, {
      waitUntil: 'networkidle0',
      timeout: 30000
    });

    let pdfBytes = Buffer.from(await page.pdf({
      format: options.format || 'A4',
      margin: options.margin || {
        top: '20mm',
        right: '20mm',
        bottom: '20mm',
        left: '20mm'
      },
      printBackground: options.printBackground !== false,
      landscape: Boolean(options.landscape),
      pageRanges: options.pageRanges || '',
      displayHeaderFooter: Boolean(options.displayHeaderFooter),
      headerTemplate: options.headerTemplate || '<span></span>',
      footerTemplate: options.footerTemplate || '<div style="font-size:9px;width:100%;text-align:center"><span class="pageNumber"></span> / <span class="totalPages"></span></div>',
      preferCSSPageSize: true
    }));

    if (limits.watermark) {
      pdfBytes = await addWatermark(
        pdfBytes,
        options.watermark || 'Generated by PdfGenerator API Free Tier'
      );
    } else if (options.watermark) {
      pdfBytes = await addWatermark(pdfBytes, options.watermark);
    }

    if (options.pdfa && !limits.watermark) {
      pdfBytes = await addArchiveMetadata(pdfBytes);
    }

    return pdfBytes;
  } finally {
    await page.close();
  }
}

async function mergePdfs(pdfUrls) {
  const merged = await PDFDocument.create();

  for (const pdfUrl of pdfUrls) {
    const url = new URL(pdfUrl);
    if (!['http:', 'https:'].includes(url.protocol)) {
      throw new Error('Only HTTP and HTTPS URLs are supported');
    }

    const response = await fetch(url, {
      signal: AbortSignal.timeout(20000),
      redirect: 'follow'
    });

    if (!response.ok) {
      throw new Error(`Unable to download PDF: ${response.status}`);
    }

    const bytes = await response.arrayBuffer();
    if (bytes.byteLength > 20 * 1024 * 1024) {
      throw new Error('A source PDF exceeds the 20 MB limit');
    }

    const source = await PDFDocument.load(bytes);
    const pages = await merged.copyPages(source, source.getPageIndices());
    pages.forEach((page) => merged.addPage(page));
  }

  return Buffer.from(await merged.save());
}

async function sendWebhook(webhookUrl, payload) {
  const response = await fetch(webhookUrl, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'User-Agent': 'PdfGenerator-Webhook/1.0'
    },
    body: JSON.stringify(payload),
    signal: AbortSignal.timeout(15000)
  });

  if (!response.ok) {
    throw new Error(`Webhook returned HTTP ${response.status}`);
  }
}

const renderWorker = new Worker(
  'pdf-render',
  async (job) => {
    const {
      jobId,
      html,
      css,
      options = {},
      webhookUrl,
      tier = 'starter'
    } = job.data;

    try {
      const pdf = await renderPdf(
        html,
        css,
        options,
        tierLimits[tier] || tierLimits.starter
      );

      await sendWebhook(webhookUrl, {
        jobId,
        status: 'completed',
        contentType: 'application/pdf',
        pdf: pdf.toString('base64')
      });

      return { jobId, status: 'completed' };
    } catch (error) {
      try {
        await sendWebhook(webhookUrl, {
          jobId,
          status: 'failed',
          error: error.message
        });
      } catch (webhookError) {
        console.error('Failure webhook delivery failed:', webhookError);
      }
      throw error;
    }
  },
  {
    connection: redis,
    concurrency: Number(process.env.RENDER_CONCURRENCY || 2)
  }
);

const mergeWorker = new Worker(
  'pdf-merge',
  async (job) => {
    const { jobId, pdfUrls, webhookUrl } = job.data;

    try {
      const pdf = await mergePdfs(pdfUrls);
      await sendWebhook(webhookUrl, {
        jobId,
        status: 'completed',
        contentType: 'application/pdf',
        pdf: pdf.toString('base64')
      });
      return { jobId, status: 'completed' };
    } catch (error) {
      try {
        await sendWebhook(webhookUrl, {
          jobId,
          status: 'failed',
          error: error.message
        });
      } catch (webhookError) {
        console.error('Failure webhook delivery failed:', webhookError);
      }
      throw error;
    }
  },
  {
    connection: redis,
    concurrency: Number(process.env.MERGE_CONCURRENCY || 2)
  }
);

renderWorker.on('failed', (job, error) => {
  console.error(`Render job ${job && job.id} failed:`, error);
});

mergeWorker.on('failed', (job, error) => {
  console.error(`Merge job ${job && job.id} failed:`, error);
});

console.log('PDF workers started');

async function shutdown() {
  await Promise.all([
    renderWorker.close(),
    mergeWorker.close()
  ]);
  if (browser) await browser.close();
  await redis.quit();
  process.exit(0);
}

process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);
